# Generated by Django 3.0.8 on 2020-07-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200704_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(default='static/photo.png', upload_to='static/'),
        ),
    ]
