# Generated by Django 3.0.8 on 2020-07-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200704_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='media/notice.jpeg', upload_to='media/notice/')),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(default='media/photo.png', upload_to='media/'),
        ),
    ]
